build_type = "Release"
components_dir = "/home/real/projects/distro2/userspace"
rootfs_dir = "/home/real/projects/distro2/rootfs"
dist_dir = "/home/real/projects/distro2/dist"
qemu_args = [
    "-bios",
    "/home/real/src/seabios/out/bios.bin",
    "-enable-kvm",
    "-m",
    "512M",
    "-append",
    "\"loglevel=6\"",
    "-smp",
    "2",
    "-net",
    "none",
    "-display",
    "gtk",
]
