# All the paths in the builder category have to be absolute
[builder]
# Build type (can only be "Release" or "Debug")
build_target = "x86_64-unknown-linux-musl"

# Directory for components
components_dir = "/path/to/userspace"

# Directory for root file system
rootfs_dir = "/path/to/rootfs"

# Build directory
dist_dir = "/path/to/dist"

[runner]
# Kernel args for QEMU to use
kernel_args = "loglevel=3"
# QEMU launch arguments
qemu_args = [
    "-enable-kvm",
    "-m",
    "512M",
    "-smp",
    "2",
    "-display",
    "gtk,zoom-to-fit=off",
    "-device",
    "virtio-gpu",
    "-hda",
    "/home/real/projects/distro2/dist/storage.qcow2",
]
